name: Build from main branch 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build and push image
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        base_image:
          - kinoite
    with:
      base-image: ${{ matrix.base_image }}
      image-tag: latest
